import type { Config } from "tailwindcss";

export default {
  theme: {
    extend: {
      colors: {
        "canvas-white": "#ffffff",
        "ink-black": "#000000",
        "stone-gray": "#c1c1c5",
        "faint-line-gray": "#d6d6d6",
        "subtle-text-gray": "#6f6f6f",
        "mid-text-gray": "#666666",
        "dark-text-gray": "#373c3b",
        "primary-purple": "#7012e2",
        "vibrant-green": "#72dd95",
        "warm-accent-orange": "#925f52",
        "fresh-accent-green": "#12e2b0",

        background: "#ffffff",
        foreground: "#000000",
        muted: "#f5f5f5",
        "muted-foreground": "#6f6f6f",
        border: "#c1c1c5",
        ring: "#12e2b0",
        primary: "#12e2b0",
        "primary-foreground": "#000000",
        secondary: "#72dd95",
        "secondary-foreground": "#000000",
        accent: "#7012e2",
        "accent-foreground": "#ffffff",
        destructive: "#925f52",
        "destructive-foreground": "#ffffff",
        warning: "#925f52",
        "warning-foreground": "#ffffff",
        success: "#72dd95",
        "success-foreground": "#000000",
        card: "#ffffff",
        "card-foreground": "#373c3b",
        sidebar: "#000000",
        "sidebar-foreground": "#ffffff",
        "sidebar-border": "#333333",
        "sidebar-active": "#12e2b0",
      },
      fontFamily: {
        nationalpark: [
          "NationalPark-Variable",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        lato: [
          "Lato",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        playfair: [
          "Playfair Display",
          "ui-serif",
          "Georgia",
          "Cambria",
          "serif",
        ],
        calistoga: [
          "Calistoga",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        patrick: [
          "Patrick Hand SC",
          "cursive",
        ],
        sans: [
          "NationalPark-Variable",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "1", letterSpacing: "0.094px" }],
        "body-sm": ["14px", { lineHeight: "1", letterSpacing: "0.094px" }],
        "body-lg": ["17px", { lineHeight: "1", letterSpacing: "0.094px" }],
        subheading: ["20px", { lineHeight: "1", letterSpacing: "0.094px" }],
        "heading-sm": ["28px", { lineHeight: "1.25" }],
        heading: ["32px", { lineHeight: "1.25" }],
        "heading-lg": ["44px", { lineHeight: "1.25" }],
        display: ["58px", { lineHeight: "1.25" }],
        "display-lg": ["106px", { lineHeight: "1" }],
      },
      borderRadius: {
        sm: "1px",
        lg: "8px",
        "2xl": "16px",
        "2xl-2": "19px",
        cards: "8px",
        buttons: "8px",
        navitems: "8px",
        largeelements: "19px",
        smallelements: "1px",
      },
      spacing: {
        4: "4px",
        6: "6px",
        8: "8px",
        10: "10px",
        12: "12px",
        13: "13px",
        14: "14px",
        15: "15px",
        16: "16px",
        24: "24px",
        27: "27px",
        32: "32px",
        42: "42px",
      },
      boxShadow: {
        subtle: "rgba(0, 0, 0, 0.08) 1px 1px 3px 0px",
        "subtle-2": "rgba(255, 255, 255, 0.32) 0px 0px 0px 1px",
      },
    },
  },
} satisfies Config;
